#  Exercício 1a
GET http://localhost:3003/staff/name?name=
Content-Type: application/json

###

#  Exercício 1b
GET http://localhost:3003/staff/type/teacher
Content-Type: application/json

###

#  Exercício 2
GET http://localhost:3003/staff/orderby?field=type
Content-Type: application/json

###

#  Exercício 3
GET http://localhost:3003/staff/pagination?page=2
Content-Type: application/json